# Generated by Django 4.1.3 on 2022-11-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="account/profile_pic"),
        ),
    ]
