# Generated by Django 4.1.3 on 2022-12-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_alter_groupmember_profile"),
        ("blog", "0002_alter_post_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="group.group"
            ),
        ),
    ]
