# Generated by Django 4.1.3 on 2022-11-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("group", "0002_alter_groupmember_group_alter_groupmember_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="user.profile",
            ),
        ),
    ]
